<?php

namespace AppBundle\Repository;

/**
 * RaceRunnerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RaceRunnerRepository extends \Doctrine\ORM\EntityRepository
{
}
